steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/padelyzer-repo/padelyzer', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/padelyzer-repo/padelyzer']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'padelyzer', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/padelyzer-repo/padelyzer', '--region', 'us-central1', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/padelyzer-backend' 