steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/padelyzer-backend', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/padelyzer-backend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'padelyzer-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/padelyzer-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'REDIS_URL=redis://redis:6379/0,CELERY_BROKER_URL=redis://redis:6379/0,CELERY_RESULT_BACKEND=redis://redis:6379/0'

images:
  - 'gcr.io/$PROJECT_ID/padelyzer-backend' 